name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: "Test composite action"
    runs-on: ubuntu-latest
    steps:

      - name: "Composite colors"
        uses: jorgepiloto/actions/logger@main
        with:
          color: "RED"
          message: "Hello Actions"

